version: 0.2

phases:
  build:
    commands:
      - git pull origin main 
      - zip -g raju_deployment_package.zip lambda_function.py 
      
  post_build:
    commands:
      - aws lambda update-function-code --function-name raju-python --zip-file fileb://raju_deployment_package.zip
    
artifacts:
  files:
    - raju_deployment_package.zip 